# Generated by Django 5.2.11 on 2026-03-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_photo_key",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
